package di.vdrchman;

public enum Command {
	ADD_USER, SET_PASSWORD, REMOVE_USER, CLEAN_DB, LOAD_SOURCES, LOAD_TRANSPONDERS, LOAD_NIDS_TIDS, LOAD_CHANNELS, CLEAN_GROUPS, LOAD_GROUPS, LOAD_CHANNEL_GROUPS, LOAD_IGNORED_CHANNELS
}
